### ISSUE TITLE
Question: How to put a border around LSPs hover popup

### ISSUE THREAD

**Issue by hristod** [Abstract-IDE/abstract-autocmds#2]
I am sorry to ask here, it's probably not the right place. Anyway, if you could answer this, it'd be great! I want to put a border around my hover popup using
`give_border` but I don't know what the pattern for that hover is. I tried with `hover` with not success, and I have no idea how to check. If you explain I am willing to help with amending the documentation to cover cases like this.

**Comment by AlixShahid** [comment]
@hristod you can just use the builtin option provided by the nvim-lspconfig
```lua
handlers["textDocument/hover"] = lsp.with(handlers.hover, {border = "single"})
```

P.S: sorry for the late reply.

have a look at [here](https://github.com/Abstract-IDE/Abstract/blob/6758bb3d1dd04523e996abd72513d6053116f761/lua/plugins/nvim-lspconfig.lua#L127-L128)

**Comment by hristod** [comment]
Thank you so much, it worked! My quest is over :D
